chore(fuels/react): add react package from npm-packs
FuelLabs/fuel-connectors pull request #167
Opened 2024-07-26 19:09 UTC by LeoCourbassier

- Moved `@fuels/react` from `npm-packs` to `connectors`
- Bumped packages version from `0.9.0` to `0.23.0` following react package's version
- Updated `react-next` example to use `defaultConnectors` from `@fuels/connectors` package

2024-08-03 22:08 UTC, LuizAsFight commented on examples/react-app/src/main.tsx
> +            wagmiConfig,
wrong change? prop stills ethWagmiConfig

2024-08-04 20:24 UTC, LuizAsFight requested changes
build is broken

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/206e1d8a-605e-462a-bd2a-2f1edb0bfbc2">

2024-08-05 17:23 UTC, LeoCourbassier commented
Audit is broken as there are no fixes for elliptic yet.
https://github.com/advisories/GHSA-f7q4-pwc6-w24p

2024-08-06 23:02 UTC, LuizAsFight approved these changes

2024-08-06 23:02 UTC, merged