feat(e2e-connector-test): CI
FuelLabs/fuel-connectors pull request #202
Opened 2024-08-24 01:17 UTC by nelitow

2024-08-27 03:02 UTC, LuizAsFight requested changes
this PR should only include CI implementation, but instead its including orthogonal changes and changes made in other PRs already

2024-08-27 03:02 UTC, LuizAsFight commented on examples/react-app/tests/FuelConnector.test.ts
> +    await page.waitForSelector('text=Fuel Wallet');
this test should not exist as they are already in the e2e-test folder

2024-08-27 03:02 UTC, LuizAsFight commented on e2e-tests/react-app/utils/connect.ts
> +};
this file dont need to exist

2024-09-09 02:07 UTC, LuizAsFight requested changes

2024-09-09 02:07 UTC, LuizAsFight commented on .github/workflows/pr-tests.yml
> +        working-directory: ./e2e-tests
- no needs to run pnpm install
- pnpm can be installed in setup-node
- install playwright with chromiun
- execute tests from script on root
- execute using "xvfb-run --auto-servernum -- " due to linux issues

```suggestion
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
          pnpm-version: 8.9.2

      - name: Install Playwright browsers
        run: pnpm exec playwright install  --with-deps chromium
        working-directory: ./e2e-tests

      - name: Run Playwright tests
        run: xvfb-run --auto-servernum -- pnpm test:e2e
        working-directory: ./e2e-tests
```

2024-09-09 02:07 UTC, LuizAsFight commented on .github/actions/e2e-tests-connectors/action.yaml
> +      run: pnpm node:clean
this file should not exist right?

2024-10-12 22:08 UTC, nelitow commented
@LuizAsFight please provide the secrets if available for the mnemonic as `VITE_MASTER_WALLET_MNEMONIC` was returning empty.

2024-10-14 22:40 UTC, closed without merging