feat(e2e-connector-test): replicate the react app in next FE-780
FuelLabs/fuel-connectors pull request #407
Opened 2024-10-15 23:25 UTC by nelitow

Goal:
Use the `react-app` components inside a Next instance and run the e2e on that with the same test suite as the React app.

2024-11-07 03:54 UTC, helciofranco commented
e2e not passing anymore after our latest changes and there are those 2 details to fix

2024-11-07 04:28 UTC, helciofranco submitted a review, later dismissed

2024-11-07 05:22 UTC, arthurgeron requested changes
Not sure if this is only on my side, but web3modal is not loading some logos:
![CleanShot 2024-11-07 at 12 21 41@2x](https://github.com/user-attachments/assets/2a906ee5-c4f7-486c-ac39-6a6bd0d37d6c)

2024-11-07 05:22 UTC, arthurgeron commented on e2e-tests/runner/.env.example
>  VITE_FUEL_PROVIDER_URL="https://testnet.fuel.network/v1/graphql"
Does it really use these env variables?

2024-11-07 05:22 UTC, arthurgeron commented on e2e-tests/react-next/.env.example
> +NEXT_PUBLIC_WC_PROJECT_ID=
best to add `NEXT_PUBLIC_PROVIDER_URL=https://testnet.fuel.network/v1/graphql` here

2024-11-07 10:34 UTC, nelitow commented
> Not sure if this is only on my side, but web3modal is not loading some logos: ![CleanShot 2024-11-07 at 12 21 41@2x](https://private-user-images.githubusercontent.com/3487334/383825188-2a906ee5-c4f7-486c-ac39-6a6bd0d37d6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzM5NjEsIm5iZiI6MTczMDk3MzY2MSwicGF0aCI6Ii8zNDg3MzM0LzM4MzgyNTE4OC0yYTkwNmVlNS1jNGY3LTQ4NmMtYWMzOS02YTZiZDBkMzdkNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMTAwMTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTkyYWUxNDU0N2EzY2RmMDNjODhkYTJkNjliZThlYTc0ZmE1ZDE3MTRmZDU0NWM3MzUzMzIyNzRmZmQ4MmUxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gg6_mD9M7ehjy52C7ch899lxQulbOM8SUFT-qQSohAE)

@arthurgeron can you let me know what is the error on your side? It loads for me.

2024-11-07 13:33 UTC, arthurgeron commented
> > Not sure if this is only on my side, but web3modal is not loading some logos: ![CleanShot 2024-11-07 at 12 21 41@2x](https://private-user-images.githubusercontent.com/3487334/383825188-2a906ee5-c4f7-486c-ac39-6a6bd0d37d6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzM5NjEsIm5iZiI6MTczMDk3MzY2MSwicGF0aCI6Ii8zNDg3MzM0LzM4MzgyNTE4OC0yYTkwNmVlNS1jNGY3LTQ4NmMtYWMzOS02YTZiZDBkMzdkNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMTAwMTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTkyYWUxNDU0N2EzY2RmMDNjODhkYTJkNjliZThlYTc0ZmE1ZDE3MTRmZDU0NWM3MzUzMzIyNzRmZmQ4MmUxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.gg6_mD9M7ehjy52C7ch899lxQulbOM8SUFT-qQSohAE)
> 
> @arthurgeron can you let me know what is the error on your side? It loads for me.

Seems like it failed with a CORS error:
![CleanShot 2024-11-07 at 20 32 58@2x](https://github.com/user-attachments/assets/13c4c504-970a-4250-84f8-0d2e808aa042)

2024-11-08 01:11 UTC, arthurgeron approved these changes

2024-11-08 01:11 UTC, merged