feat(e2e-connector-tests): unify connector tests FE-860
FuelLabs/fuel-connectors pull request #422
Opened 2024-10-30 19:55 UTC by nelitow

This PR makes the tests generic, with the idea of importing the tests needed for each connector, instead of rewriting them for every item on the connectors list.
This is in preparation for having the same test suite for all connectors.

2024-11-08 05:46 UTC, helciofranco submitted a review, later dismissed

2024-11-08 06:02 UTC, LuizAsFight requested changes

2024-11-08 06:02 UTC, LuizAsFight commented on e2e-tests/runner/examples/connectors/FuelWalletConnector/FuelWalletConnector.test.ts
>  const fuelPathToExtension = await downloadFuel('0.40.1');
can we update to 0.41.1 ?

2024-11-10 16:14 UTC, arthurgeron commented on .github/workflows/pr-tests.yml
>          env:
We could have all these envs in the runner's .env.example, so it's easier for anyone to run them theirselves when needed.

2024-11-12 01:52 UTC, arthurgeron approved these changes

2024-11-12 03:52 UTC, helciofranco approved these changes
great stuff

2024-11-12 12:24 UTC, merged