feat: ethereum wallets connector
FuelLabs/fuel-connectors pull request #43
Opened 2024-04-06 19:15 UTC by pedropereiradev

2024-04-10 23:50 UTC, luizstacio requested changes
Also the tests are failing because of lack of coverage, I understand it can be difficult to mock the walletconnect modal, if you don't find a ready solution, you can reduce the trashhold of the test coverage for the specific package.

2024-04-10 23:50 UTC, luizstacio commented on examples/react-app/.env
> +VITE_APP_WC_PROJECT_ID=0e0f5503e675e719c07e73ff5f38d31f
we need to ignore this file from github

2024-04-10 23:50 UTC, luizstacio commented on examples/react-app/src/main.tsx
> +const _queryClientt = new QueryClient();
```suggestion
const queryClient = new QueryClient();
```

2024-04-10 23:50 UTC, luizstacio commented on packages/evm-connector/src/EvmWalletConnector.ts
> +        //@ts-ignore
Why you need this `@ts-ignore`?

2024-04-10 23:50 UTC, luizstacio commented on packages/walletconnect-connector/src/types.ts
> +}
??

2024-04-12 16:50 UTC, luizstacio requested changes

2024-04-12 16:50 UTC, luizstacio commented on examples/react-app/src/main.tsx
> +  chains: [mainnet],
Can you add here sepolia also?

2024-04-16 11:53 UTC, HoTandy reviewed
I've raised the following issues here:
https://github.com/FuelLabs/fuel-connectors/issues/54
https://github.com/FuelLabs/fuel-connectors/issues/53

With the Ethereum Wallets connection option, I'm finding it virtually impossible to connect to Trust wallet or Coinbase wallet with the Sepolia network. I'm wondering if this is a problem on their side though rather than on the Fuel side.
I think I had this problem when I first started to test Connectors and then tried to Connect Metamask, ...it ended up that a fix was possible on the Fuel side. (https://github.com/FuelLabs/fuel-connectors/issues/35)
Will it be the same with these other wallets?  Linking up with mainnets is never an issue.

WalletConnect I can scan with the camera on my iPhone (I don't have an Android phone), it always wants to open Metamask which I would kind of expect with iOS.  It's always impossible to change the default app on iOS.
I can scan the WalletConnect QR codes from within different wallet apps though and each time is seems to work ok, except it always want to connect Mainnet addresses to the Fuel Connector.
I cannot imagine that this is something that can be changed on the Fuel side, or is it?

2024-04-18 19:16 UTC, luizstacio commented
close in favor of #61

2024-04-18 19:16 UTC, closed without merging