feat: set default chain to mainnet
FuelLabs/fuel-connectors pull request #450
Opened 2024-12-30 13:58 UTC by helciofranco

- Closes https://github.com/FuelLabs/fuel-connectors/issues/423

2024-12-30 14:58 UTC, helciofranco commented
E2E failing due to a broken link https://crx-backup.phantom.dev/latest.crx

2025-01-03 04:55 UTC, LuizAsFight requested changes

2025-01-03 04:55 UTC, LuizAsFight commented on packages/burner-wallet-connector/src/BurnerWalletConnector.ts
> +    const network = getProviderUrl(config.chainId ?? CHAIN_IDS.fuel.mainnet);
this will be a breaking change we should not change in case of burner wallet because its not used on mainnet, only on testnet

2025-01-06 07:21 UTC, helciofranco commented on packages/burner-wallet-connector/src/BurnerWalletConnector.ts
> +    const network = getProviderUrl(config.chainId ?? CHAIN_IDS.fuel.mainnet);
got it

https://github.com/FuelLabs/fuel-connectors/pull/450/commits/0669161456f23c6603124dc0d342cdeab5c1cee3

2025-01-06 20:10 UTC, LuizAsFight approved these changes

2025-01-06 20:10 UTC, merged